### ISSUE TITLE
katcp.Sensor, params not formatted properly

### ISSUE THREAD

**Issue by carterb23** [ska-sa/katcp-python#229]
Python 3.7:
Following error on v0.7.0 when setting up a sensor:
`sens_type = Sensor.parse_type('float')`
`test_sens = Sensor( sensor_type=sens_type, name='test', params=['0', '1', '2', '3'])`
whereas 
`test_sens = Sensor( sensor_type=sens_type, name='test', params=[0, 1, 2, 3])`
works. Sensor class description says:

>@var params
   @brief List of strings containing the additional parameters (length and
   interpretation are specific to the sensor type).

ERROR:
> Traceback (most recent call last):
  File "E:/Workspace/Projects/MPIfR/GIM/software/python/katcp_client/client_callback.py", line 29, in <module>
    main()
  File "E:/Workspace/Projects/MPIfR/GIM/software/python/katcp_client/client_callback.py", line 22, in main
    client = KatcpClient(opts.host, opts.port)
  File "E:\Workspace\Projects\MPIfR\GIM\software\python\katcp_client\esg3_katcp\katcp_client.py", line 87, in __init__
    params=['0', '1', '2', '3']
  File "C:\Program Files (x86)\Python3\lib\site-packages\katcp\core.py", line 1098, in __init__
    self.formatted_params = [self._formatter(p, True) for p in params]
  File "C:\Program Files (x86)\Python3\lib\site-packages\katcp\core.py", line 1098, in <listcomp>
    self.formatted_params = [self._formatter(p, True) for p in params]
  File "C:\Program Files (x86)\Python3\lib\site-packages\katcp\kattypes.py", line 115, in pack
    return self.encode(value, major)
  File "C:\Program Files (x86)\Python3\lib\site-packages\katcp\kattypes.py", line 205, in encode
    raise ValueError("Could not encode value '%r' as float." % value)
ValueError: Could not encode value ''0'' as float.

**Comment by ajoubertza** [comment]
Hi @carterb23 

Thanks for the report.  I think the behaviour is correct, but the docstring is confusing.  For a float sensor, the parameters (which are optional) are the minimum and maximum values the float sensor is expected to have.  They need to be numeric (so int or float).

The docstring for the `Sensor` class mentions `params` twice.  The first one is correct (although it doesn't mention the type of the items in the list explicitly).

First mention:
https://github.com/ska-sa/katcp-python/blob/b3468dc39eec96aaa2db44e62fdec76c29784bd5/katcp/core.py#L917-L925

Second mention:
https://github.com/ska-sa/katcp-python/blob/b3468dc39eec96aaa2db44e62fdec76c29784bd5/katcp/core.py#L1029-L1031

The first mention is also the one that ends up on readthedocs:
https://katcp-python.readthedocs.io/en/v0.7.0/api.html#sensor

I will try to make the documentation a little clearer.

#### Other notes:

I'm not sure if you specifically want to create the sensors with the type dynamically, thus the use of `Sensor.parse_type('float')`.  If not, there is a shorter way of instantiating the float sensors:
```python
test_sens = Sensor.float(name='test', params=[0, 1])
```

Also note that the min and maximum parameters for float and int sensors don't do much.  They are only for information, and don't limit the values assigned to the sensor.  Supplying more than 2 parameters for a float sensor doesn't make sense either.  Either provide 2 - the min and max, or provide none.

**Comment by ajoubertza** [comment]
@carterb23 I'm going to close this issue tomorrow, unless you still have questions or comments.

**Comment by carterb23** [comment]
@ajoubertza: Thanks for the info! Wouldn't it be more consistent to implement the convert/cast functionality in the Sensor class. There you have all the information needed and it is done on many other places in the module the same way (passing string value and conversion/cast is done in the class). From my understanding, dealing with sensor types fits best in the Sensor class (but that's my opinion).

**Comment by ajoubertza** [comment]
Yes, the `params` could be more forgiving and do a some validation on the type.  As for consistency,  many of the methods in this core module are strict about the types, so I'm not convinced that the `Sensor` constructor is going against the established pattern.

You're welcome to submit a pull request if you feel strongly that the behaviour of `params` initialisation should be changed.

**Comment by carterb23** [comment]
I thought the same. I need this functionality for my app either way. Let's see how it goes.
